[global]
   workgroup = WORKGROUP
   server string = Samba Server %v
   netbios name = samba
   security = user
   map to guest = bad user
   dns proxy = no

#============================ Share Definitions ==============================

[homes]
   comment = Home Directories
   browseable = no
   read only = yes
   create mask = 0700
   directory mask = 0700
   valid users = %S

[printers]
   comment = All Printers
   browseable = no
   path = /var/spool/samba
   printable = yes
   guest ok = no
   read only = yes
   create mask = 0700

[shared]
   comment = Shared Files
   path = /srv/samba/shared
   browseable = yes
   read only = no
   guest ok = no
   valid users = @sambashare
   create mask = 0664
   directory mask = 0775
